version: '3'
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile_flask_app
    # Filas to scale when custom_name and port mapping are set
    # container_name: web
    # ports:
    #   - "5000:5000"
    env_file:
      - web/.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    volumes:
      - ods:/var/lib/postgresql/data
    restart: always
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: db
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile_nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - web
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  ods:
  redis:
