version: '3'
services:
  web:
    build: ./web
    container_name: web
    ports:
      - "5000:5000"
    env_file:
      - web/.env
    links:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    volumes:
      - ods:/var/lib/postgresql/data
    restart: always
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  ods:
